name: Android App Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.11.9
      JAVA_VERSION: 11
      ANDROID_SDK_VERSION: "commandlinetools-linux-9477386_latest.zip"
      NDK_VERSION: "23.1.7779620"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # You can use 'adopt' or 'zulu' if preferred
        java-version: ${{ env.JAVA_VERSION }}

    - name: Install Android SDK
      run: |
        sudo mkdir -p /usr/local/lib/android/sdk
        cd /usr/local/lib/android/sdk
        wget https://dl.google.com/android/repository/${{ env.ANDROID_SDK_VERSION }}
        unzip ${{ env.ANDROID_SDK_VERSION }}
        rm ${{ env.ANDROID_SDK_VERSION }}
        yes | ./cmdline-tools/bin/sdkmanager --licenses
        ./cmdline-tools/bin/sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Install NDK
      run: |
        /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/emulator" >> $GITHUB_ENV

    - name: Build Android APK
      run: |
        buildozer android debug
