name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Using the latest version

      # Get Date and set environment variable
      - name: Get Date
        id: get-date
        run: echo "DATE=$(date -u '+%Y%m%d')" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v3 # Updated to v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v3 # Updated to v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.DATE }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
