name: Build Drowsiness Detection App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-17-jdk libgl1-mesa-glx libglib2.0-0 wget unzip git
        python3 -m pip install --upgrade pip
        pip3 install buildozer cython==0.29.33
        
        # Install required Python libraries
        pip3 install opencv-python==4.10.0.84
        pip3 install mediapipe==0.10.15
        pip3 install numpy
        pip3 install scipy==1.10.1
        pip3 install ultralytics==8.3.7
        pip3 install pillow
        pip3 install kivy==2.3.0
        
        # Add buildozer to PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Android SDK & NDK
      run: |
        # Set up environment variables for SDK and NDK
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android-sdk/emulator" >> $GITHUB_PATH
        
        # Create directories for SDK and NDK
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        
        # Download and install the SDK command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        
        # Accept licenses
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # Install platform tools, build-tools, platform, and NDK
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33" "ndk;25.2.9519653"

    - name: Build the APK
      run: |
        buildozer android debug
      env:
        ANDROIDSDK: ${{ env.ANDROID_SDK_ROOT }}
        ANDROIDNDK: ${{ env.ANDROID_NDK_ROOT }}
        ANDROIDAPI: '33'
        ANDROIDMINAPI: '21'

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
