name: Build Drowsiness Detection App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Install Python dependencies and system tools
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-17-jdk libgl1-mesa-glx libglib2.0-0 wget unzip
        pip install --upgrade pip
        pip install buildozer
        
        # Install required Python libraries
        pip install opencv-python==4.10.0.84
        pip install mediapipe==0.10.15
        pip install numpy
        pip install scipy==1.10.1
        pip install ultralytics==8.3.7
        pip install pillow
        pip install kivy==2.3.0

    # Set up Android SDK and NDK
    - name: Install Android SDK & NDK
      run: |
        # Set up environment variables for SDK and NDK
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator
        
        # Create directories for SDK and NDK
        mkdir -p $ANDROID_SDK_ROOT
        cd $ANDROID_SDK_ROOT
        
        # Download and install the SDK command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        
        # Accept all licenses
        yes | sdkmanager --licenses
        
        # Install platform tools, build tools, and SDK platform
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.2.9519653"

    # Build the APK using Buildozer
    - name: Build the APK
      run: |
        buildozer android debug
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROIDNDK: $ANDROID_SDK_ROOT/ndk/25.2.9519653
        ANDROIDAPI: '33'
        ANDROIDMINAPI: '21'
