name: Android App Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.11.9
      JAVA_VERSION: 11
      ANDROID_SDK_VERSION: "commandlinetools-linux-9477386_latest.zip"
      NDK_VERSION: "25.2.9519653"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython buildozer

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Install Android SDK
      run: |
        # Create the SDK directory
        sudo mkdir -p /usr/local/lib/android/sdk
        # Download and extract the SDK command-line tools
        cd /usr/local/lib/android/sdk
        wget https://dl.google.com/android/repository/${{ env.ANDROID_SDK_VERSION }} -O commandlinetools.zip
        unzip commandlinetools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        rm commandlinetools.zip
        # Accept licenses and install required SDK components
        yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Install NDK
      run: |
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

    - name: Install Additional SDK Tools (aidl)
      run: |
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "sources;android-30" --sdk_root=/usr/local/lib/android/sdk
    
    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/emulator" >> $GITHUB_ENV

    - name: Build Android APK
      run: |
        buildozer android debug
