name: Android App Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.11.9
      JAVA_VERSION: 11
      ANDROID_SDK_VERSION: "commandlinetools-linux-9477386_latest.zip"
      NDK_VERSION: "25.2.9519653"
      ANDROID_HOME: "/usr/local/lib/android/sdk"
      ANDROID_SDK_ROOT: "/usr/local/lib/android/sdk"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython buildozer

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Install Android SDK
      run: |
        # Create the SDK directory
        sudo mkdir -p $ANDROID_HOME
        # Download and extract the SDK command-line tools
        cd $ANDROID_HOME
        wget https://dl.google.com/android/repository/${{ env.ANDROID_SDK_VERSION }} -O commandlinetools.zip
        unzip commandlinetools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        rm commandlinetools.zip
        # Accept licenses and install required SDK components
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
          "platform-tools" \
          "platforms;android-30" \
          "build-tools;30.0.3" \
          "sources;android-30"

    - name: Install NDK
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=${{ env.ANDROID_HOME }}" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=${{ env.ANDROID_HOME }}" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV
        echo "PATH=$PATH:${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:${{ env.ANDROID_HOME }}/platform-tools:${{ env.ANDROID_HOME }}/emulator" >> $GITHUB_ENV

    - name: Build Android APK
      run: |
        buildozer android debug
